### ISSUE TITLE
Any plan to add support of A Plague Tale Innocence DPC files?

### ISSUE THREAD

**Issue by Detector-I** [widberg/fmtk#1]
Hi, thank you for great work
I want to know there is any chance to add support of **A Plague Tale Innocence** DPC file format to this tool?
especially I interest in change default game **fonts**, but I cant work with DPC file format...

**Comment by widberg** [comment]
The DPC format used by A Plague Tale: Innocence uses version 2.128.92.19 and FUEL uses versions 1.220.50.07 to 1.381.67.09. There are most likely some differences between the two requiring minor changes to the `dpc` project to parse A Plague Tale: Innocence's DPC files. I have no plans to support versions not used by FUEL but all of the format specifications for FUEL will be available if another user would like to use that to support A Plague Tale: Innocence. akderebur has done some great work on their [A Plague Tale: Innocence Tool](https://forum.xentax.com/viewtopic.php?t=20481) in supporting textures, meshes, and skeletons. In the future I may add support for other versions but at the moment the only Asobo game I own is FUEL and a large part of my research involves monitoring the running game through the loading process so I am unable to research other versions right now.

**Comment by YouKnow-sys** [comment]
> The DPC format used by A Plague Tale: Innocence uses version 2.128.92.19 and FUEL uses versions 1.220.50.07 to 1.381.67.09. There are most likely some differences between the two requiring minor changes to the `dpc` project to parse A Plague Tale: Innocence's DPC files. I have no plans to support versions not used by FUEL but all of the format specifications for FUEL will be available if another user would like to use that to support A Plague Tale: Innocence. akderebur has done some great work on their [A Plague Tale: Innocence Tool](https://forum.xentax.com/viewtopic.php?t=20481) in supporting textures, meshes, and skeletons. In the future I may add support for other versions but at the moment the only Asobo game I own is FUEL and a large part of my research involves monitoring the running game through the loading process so I am unable to research other versions right now.

thank you, yes I checked akderebur tool and its very good but sadly its only work for texture, mash and skeleton as you said...
and not usable for anything else and its not even open source so I can check it...
I hope you after finished your research on this game take a look at older dpc format, thanks anyway

**Comment by Detector-I** [comment]
> The DPC format used by A Plague Tale: Innocence uses version 2.128.92.19 and FUEL uses versions 1.220.50.07 to 1.381.67.09. There are most likely some differences between the two requiring minor changes to the `dpc` project to parse A Plague Tale: Innocence's DPC files. I have no plans to support versions not used by FUEL but all of the format specifications for FUEL will be available if another user would like to use that to support A Plague Tale: Innocence. akderebur has done some great work on their [A Plague Tale: Innocence Tool](https://forum.xentax.com/viewtopic.php?t=20481) in supporting textures, meshes, and skeletons. In the future I may add support for other versions but at the moment the only Asobo game I own is FUEL and a large part of my research involves monitoring the running game through the loading process so I am unable to research other versions right now.

thank you, yes I checked akderebur tool and its very good but sadly its only usable for texture, mash and skeleton as you said, and not for anything else and its not even open source so I can check it... (I tried to send msg to akderebur but he didn't answer me back)
I hope you after finished your research on this game take a look at older dpc format, thanks anyway

**Comment by widberg** [comment]
FUEL's Fonts_Z format has been reversed here https://github.com/widberg/fmtk/wiki/Fonts_Z and there is now a project named `noesis_fuel_pc` in the main directory of this repo. If anyone comes across this and wants to try adding APT support to the noesis plugin I'll happily merge a pull request. I've artificially locked the DPC extractor to FUEL's version strings but there is a chance it will work on APT files without any changes.
